# CREATE AN ARRAY

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [4]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [7]:
np.arange(7,34)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [8]:
np.arange(10,98,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,4)

array([[0.72652614, 0.72398839, 0.02212955, 0.60250759],
       [0.31909433, 0.94937579, 0.19245398, 0.10565503]])

In [18]:
np.random.randn(2,4)

array([[-0.90542672, -0.19136483,  0.45492764,  1.35489357],
       [-0.93446321, -0.07301715,  2.00049702, -1.53157723]])

In [19]:
np.random.randint(1,25,10)

array([15,  5,  2,  4,  8, 14,  3,  5, 18,  1])

In [21]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
rand_array=np.random.randint(0,10,5)
rand_array

array([4, 8, 7, 1, 1])

In [23]:
sample_array.min()

2

In [24]:
sample_array.argmin()

0

In [25]:
rand_array.min()

1

In [26]:
rand_array.argmin()

3

In [ ]:
#### Code to import numpy?
#### Create an array of 10 zeroes with integer datatype.
#### Create normal distribution of shape 2x5.
#### Create unit vector of float data type with shape 3x7
#### Identity matrix of 10x10
#### O/p:5,10,15,20,25

In [29]:
import numpy as np

In [30]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.random.randn(2,5)

array([[ 1.68738485, -0.43261963, -0.02073068,  0.76219452,  1.89334553],
       [ 0.19177419, -1.84113719, -0.68933948,  0.29795484,  1.93789647]])

In [32]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [35]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [37]:
arr=np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [39]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [40]:
np.linspace(5,25,5)

array([ 5., 10., 15., 20., 25.])

# PANDAS DATAFRAME AND INDEXING

In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','baseball','golf'])
sports1

cricket     1
football    2
baseball    3
golf        4
dtype: int64

In [8]:
sports1['golf']

4

In [9]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [10]:
sports1+sports2

cricket     12
football    15
baseball    15
golf         8
dtype: int64

In [11]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.369873  0.093190  0.473611  0.814606  0.892810
B  0.192904  0.416220  0.558021  0.686033  0.868608
C  0.982872  0.927229  0.431206  0.545069  0.695994
D  0.132582  0.062581  0.451641  0.733754  0.018985
E  0.512164  0.803711  0.086148  0.446520  0.496326
F  0.050600  0.467318  0.143922  0.863569  0.503383
G  0.997777  0.611008  0.943775  0.774197  0.641387
H  0.842489  0.434223  0.181059  0.446242  0.188858

In [12]:
df1['Score3']

A    0.473611
B    0.558021
C    0.431206
D    0.451641
E    0.086148
F    0.143922
G    0.943775
H    0.181059
Name: Score3, dtype: float64

In [13]:
df1[['Score1','Score2','Score3']]

Score1    Score2    Score3
A  0.369873  0.093190  0.473611
B  0.192904  0.416220  0.558021
C  0.982872  0.927229  0.431206
D  0.132582  0.062581  0.451641
E  0.512164  0.803711  0.086148
F  0.050600  0.467318  0.143922
G  0.997777  0.611008  0.943775
H  0.842489  0.434223  0.181059

In [14]:
df1[['Score4','Score2','Score5']]

Score4    Score2    Score5
A  0.814606  0.093190  0.892810
B  0.686033  0.416220  0.868608
C  0.545069  0.927229  0.695994
D  0.733754  0.062581  0.018985
E  0.446520  0.803711  0.496326
F  0.863569  0.467318  0.503383
G  0.774197  0.611008  0.641387
H  0.446242  0.434223  0.188858

In [15]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.369873  0.093190  0.473611  0.814606  0.892810  0.463063
B  0.192904  0.416220  0.558021  0.686033  0.868608  0.609125
C  0.982872  0.927229  0.431206  0.545069  0.695994  1.910101
D  0.132582  0.062581  0.451641  0.733754  0.018985  0.195164
E  0.512164  0.803711  0.086148  0.446520  0.496326  1.315875
F  0.050600  0.467318  0.143922  0.863569  0.503383  0.517918
G  0.997777  0.611008  0.943775  0.774197  0.641387  1.608785
H  0.842489  0.434223  0.181059  0.446242  0.188858  1.276712

In [16]:
df1.drop("Score3",axis=1)

Score1    Score2    Score4    Score5    Score6
A  0.369873  0.093190  0.814606  0.892810  0.463063
B  0.192904  0.416220  0.686033  0.868608  0.609125
C  0.982872  0.927229  0.545069  0.695994  1.910101
D  0.132582  0.062581  0.733754  0.018985  0.195164
E  0.512164  0.803711  0.446520  0.496326  1.315875
F  0.050600  0.467318  0.863569  0.503383  0.517918
G  0.997777  0.611008  0.774197  0.641387  1.608785
H  0.842489  0.434223  0.446242  0.188858  1.276712

In [22]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.369873  0.093190  0.473611  0.814606  0.892810  0.463063
B  0.192904  0.416220  0.558021  0.686033  0.868608  0.609125
C  0.982872  0.927229  0.431206  0.545069  0.695994  1.910101
D  0.132582  0.062581  0.451641  0.733754  0.018985  0.195164
F  0.050600  0.467318  0.143922  0.863569  0.503383  0.517918
G  0.997777  0.611008  0.943775  0.774197  0.641387  1.608785
H  0.842489  0.434223  0.181059  0.446242  0.188858  1.276712

In [23]:
df1.drop('Score1',axis=1)

Score2    Score3    Score4    Score5    Score6
A  0.093190  0.473611  0.814606  0.892810  0.463063
B  0.416220  0.558021  0.686033  0.868608  0.609125
C  0.927229  0.431206  0.545069  0.695994  1.910101
D  0.062581  0.451641  0.733754  0.018985  0.195164
E  0.803711  0.086148  0.446520  0.496326  1.315875
F  0.467318  0.143922  0.863569  0.503383  0.517918
G  0.611008  0.943775  0.774197  0.641387  1.608785
H  0.434223  0.181059  0.446242  0.188858  1.276712

In [24]:
df1.drop("A",axis=0)

Score1    Score2    Score3    Score4    Score5    Score6
B  0.192904  0.416220  0.558021  0.686033  0.868608  0.609125
C  0.982872  0.927229  0.431206  0.545069  0.695994  1.910101
D  0.132582  0.062581  0.451641  0.733754  0.018985  0.195164
E  0.512164  0.803711  0.086148  0.446520  0.496326  1.315875
F  0.050600  0.467318  0.143922  0.863569  0.503383  0.517918
G  0.997777  0.611008  0.943775  0.774197  0.641387  1.608785
H  0.842489  0.434223  0.181059  0.446242  0.188858  1.276712

In [25]:
df1.drop(["Score1","Score2"],axis=1)

Score3    Score4    Score5    Score6
A  0.473611  0.814606  0.892810  0.463063
B  0.558021  0.686033  0.868608  0.609125
C  0.431206  0.545069  0.695994  1.910101
D  0.451641  0.733754  0.018985  0.195164
E  0.086148  0.446520  0.496326  1.315875
F  0.143922  0.863569  0.503383  0.517918
G  0.943775  0.774197  0.641387  1.608785
H  0.181059  0.446242  0.188858  1.276712

In [17]:
df2={'ID':[101,102,103,107,176],'NAME':['John','mercy','akash','kavin','lally'],'Profit':[20,54,56,87,95]}
df=pd.DataFrame(df2)
df

ID   NAME  Profit
0  101   John      20
1  102  mercy      54
2  103  akash      56
3  107  kavin      87
4  176  lally      95

In [18]:
df.drop('ID',axis=1)

NAME  Profit
0   John      20
1  mercy      54
2  akash      56
3  kavin      87
4  lally      95

In [19]:
df.drop(3)

ID   NAME  Profit
0  101   John      20
1  102  mercy      54
2  103  akash      56
4  176  lally      95

In [20]:
df[['NAME','Profit']]

NAME  Profit
0   John      20
1  mercy      54
2  akash      56
3  kavin      87
4  lally      95

In [21]:
df[['NAME','ID']]

NAME   ID
0   John  101
1  mercy  102
2  akash  103
3  kavin  107
4  lally  176